### ISSUE TITLE
Problem on IE11

### ISSUE THREAD

**Issue by dan3460** [ConsoleTVs/Charts#582]
Charts not showing on IE11, working fine on Chrome and Firefox. On IE11 getting the following message warning:
```
HTML1300: Navigation occurred.
credit
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
credit (40,9)
HTML1508: Unmatched end tag.
credit (58,1)
jQuery.Deferred exception: 'fetch' is undefined ReferenceError: 'fetch' is undefined
   at t.prototype.request (https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js:29:9566)
   at t.prototype.update (https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js:29:10638)
   at t.prototype.bootstrap (https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js:29:9496)
   at t (https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js:29:8644)
   at n (https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js:29:16900)
   at Anonymous function (http://10.1.10.7/credit:5964:9)
   at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29367)
   at Anonymous function (https://code.jquery.com/jquery-3.3.1.min.js:2:29677) undefined
```
and the following error:
```
SCRIPT5009: 'fetch' is undefined
jquery-3.3.1.min.js (2,31040)
```

**Comment by ConsoleTVs** [comment]
Here's what you need:

https://github.com/github/fetch

This polyfill will fix your issue ^^
